version: '3'
services:
    influxdb:
        image: "influxdb"
        ports:
         - "8086:8086"
        volumes:
         - "/var/lib/influxdb:/var/lib/influxdb"
    grafana:
        depends_on:
         - "influxdb"
        image: "grafana/grafana"
        environment:
         - GF_INSTALL_PLUGINS=grafana-clock-panel,jdbranham-diagram-panel,grafana-piechart-panel,snuids-radar-panel,snuids-trafficlights-panel,btplc-trend-box-panel,grafana-worldmap-panel
        ports:
         - "3000:3000"
        volumes:
         - "/var/lib/grafana:/var/lib/grafana"